fix(runnable): Fix runnable blocks 404-ing. (#66)
This adds a semi-colon to terminate the variable declaration for DGRAPH_ENDPOINT
used for runnables.

The variable declaration for `window.DGRAPH_ENDPOINT` needs to end in a
semi-colon or else it gets interpreted as a function call with the next line in
the script.

    Uncaught TypeError: "https://play.dgraph.io/query?latency=true" is not a function
        at (index):451